version: '2' 

services:
  database:
    image: mysql:5.5
    container_name: database
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - .:/rails-server
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE = database
      - MYSQL_USER = user_testdb
      - MYSQL_PASSWORD = 123456

  rails: #name of the second service
    build: . # specify the directory of the Dockerfile
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/rails-server
      - web_rubygems:/usr/local/bundle
    ports:
      - "3000:3000" #specify ports forewarding
    restart: always
    links:
      - database # link this service to the database service
volumes:
  db_data:
  web_rubygems: